version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6666:6379

  database:
    image: postgres:latest
    container_name: database
    ports:
      - 5555:5432
    env_file:
      - ./app/db/.env

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - database
